// REDUX ACTION TYPES
export const ALERTS_REQUEST = 'ALERTS_REQUEST'
export const ALERTS_ERROR = 'ALERTS_ERROR'
export const ALERTS_SUCCESS = 'ALERTS_SUCCESS'

export const ALERT_BY_ID_REQUEST = 'ALERT_BY_ID_REQUEST'
export const ALERT_BY_ID_ERROR = 'ALERT_BY_ID_ERROR'
export const ALERT_BY_ID_SUCCESS = 'ALERT_BY_ID_SUCCESS'

