// REDUX ACTION TYPES
//ALERTS
export const ALERTS_REQUEST = 'ALERTS_REQUEST'
export const ALERTS_ERROR = 'ALERTS_ERROR'
export const ALERTS_SUCCESS = 'ALERTS_SUCCESS'

export const ALERT_BY_ID_REQUEST = 'ALERT_BY_ID_REQUEST'
export const ALERT_BY_ID_ERROR = 'ALERT_BY_ID_ERROR'
export const ALERT_BY_ID_SUCCESS = 'ALERT_BY_ID_SUCCESS'

//AGENTS
export const AGENTS_REQUEST = 'AGENTS_REQUEST'
export const AGENTS_ERROR = 'AGENTS_ERROR'
export const AGENTS_SUCCESS = 'AGENTS_SUCCESS'

export const AGENT_BY_ID_REQUEST = 'AGENT_BY_ID_REQUEST'
export const AGENT_BY_ID_ERROR = 'AGENT_BY_ID_ERROR'
export const AGENT_BY_ID_SUCCESS = 'AGENT_BY_ID_SUCCESS'

//RULES
export const RULES_REQUEST = 'RULES_REQUEST'
export const RULES_ERROR = 'RULES_ERROR'
export const RULES_SUCCESS = 'RULES_SUCCESS'

export const RULE_BY_ID_REQUEST = 'RULE_BY_ID_REQUEST'
export const RULE_BY_ID_ERROR = 'RULE_BY_ID_ERROR'
export const RULE_BY_ID_SUCCESS = 'RULE_BY_ID_SUCCESS'

